#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_NAME="$(basename "$0")"
readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PROVIDER="openai"
ENV_FILE="${REPO_ROOT}/.env"

usage() {
  cat <<EOF
Interactively configure the optional react-recon LLM analyst.

Usage: ${SCRIPT_NAME} [OPTIONS]

Options:
  --provider VALUE  Active provider: openai, anthropic, or both
                    (both prompts for the active provider)
  --env-file PATH   Destination environment file (default: repository .env)
  -h, --help        Show this help text

The API key is read without terminal echo and is never sent to a validation
endpoint. The resulting environment file is created with mode 600.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

while (($#)); do
  case "$1" in
    --provider)
      (($# >= 2)) || die "--provider requires a value"
      PROVIDER="$2"
      shift 2
      ;;
    --env-file)
      (($# >= 2)) || die "--env-file requires a path"
      ENV_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

case "${PROVIDER}" in
  openai|anthropic) ;;
  both)
    read -r -p "Active analysis provider [openai]: " selected_provider
    PROVIDER="${selected_provider:-openai}"
    [[ "${PROVIDER}" == "openai" || "${PROVIDER}" == "anthropic" ]] || die "active provider must be openai or anthropic"
    ;;
  *) die "unsupported provider '${PROVIDER}'; use openai, anthropic, or both" ;;
esac

if [[ -e "${ENV_FILE}" ]]; then
  read -r -p "${ENV_FILE} already exists. Replace it? [y/N]: " replace
  [[ "${replace}" =~ ^[Yy]$ ]] || die "configuration cancelled; existing file was not changed"
fi

if [[ "${PROVIDER}" == "openai" ]]; then
  default_model="gpt-5.6-luna"
  key_label="OpenAI"
else
  default_model="claude-sonnet-5"
  key_label="Anthropic"
fi

read -r -p "Model [${default_model}]: " model
model="${model:-${default_model}}"
[[ "${model}" =~ ^[A-Za-z0-9._:/-]+$ ]] || die "model contains unsupported characters"

read -r -s -p "${key_label} API key: " api_key
printf '\n'
[[ -n "${api_key}" ]] || die "API key cannot be empty"
[[ "${api_key}" != *$'\n'* && "${api_key}" != *$'\r'* ]] || die "API key cannot contain line breaks"

env_dir="$(dirname "${ENV_FILE}")"
mkdir -p "${env_dir}"
umask 077
temporary_env="$(mktemp "${env_dir}/.react-recon-env.XXXXXX")"
trap 'rm -f "${temporary_env}"' EXIT

{
  printf '# Generated by scripts/configure-provider.sh\n'
  printf 'REACT_RECON_AI_PROVIDER=%q\n' "${PROVIDER}"
  printf 'REACT_RECON_AI_MODEL=%q\n' "${model}"
  if [[ "${PROVIDER}" == "openai" ]]; then
    printf 'OPENAI_API_KEY=%q\n' "${api_key}"
    printf 'ANTHROPIC_API_KEY=\n'
  else
    printf 'OPENAI_API_KEY=\n'
    printf 'ANTHROPIC_API_KEY=%q\n' "${api_key}"
  fi
  printf 'REACT_RECON_DATABASE=react-recon.db\n'
  printf 'REACT_RECON_EVIDENCE_DIR=evidence\n'
} >"${temporary_env}"

chmod 600 "${temporary_env}"
mv "${temporary_env}" "${ENV_FILE}"
trap - EXIT

printf 'Configured %s analysis with model %s in %s (mode 600).\n' "${PROVIDER}" "${model}" "${ENV_FILE}"
printf 'The key was stored locally and was not validated over the network.\n'
